name: Docker Build

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: myproject-repository
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write # Required if you want to see results in the Security tab

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true # CRITICAL: This pulls the image from Buildx into the local Docker daemon
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: KICS scan
        uses: checkmarx/kics-github-action@v2.1.0
        with:
          path: '.'
          platforms: 'Dockerfile,Kubernetes,Terraform'
          output_path: 'kics-results'
          output_formats: 'json,sarif'
          exclude_paths: "node_modules/"
          
      - name: Run Trivy SCA (Vulnerabilities, Secrets, Config)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          scanners: 'vuln,secret,misconfig'
          severity: 'CRITICAL,HIGH'
      # --- TRIVY SCAN END ---

      - name: Build and Scan complete
        run: echo "Docker image built and scanned successfully - ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
